/**
 * CodeSpirit 笔记本页面
 */

import { useState, useEffect } from 'react';
import {
  NotebookPen,
  Plus,
  Search,
  Trash2,
  Edit3,
  Download,
  FolderOpen,
  MoreVertical,
  Save,
  X,
  Eye
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent } from '@/components/ui/card';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Badge } from '@/components/ui/badge';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { getAll, put, remove, STORES } from '@/db';
import { downloadFile, generateId } from '@/utils';
import type { Note } from '@/types';
import type { PageType } from '@/App';
import { toast } from 'sonner';

interface NotesPageProps {
  onNavigate: (page: PageType, params?: any) => void;
}

export function NotesPage({ onNavigate }: NotesPageProps) {
  const [notes, setNotes] = useState<Note[]>([]);
  const [categories, setCategories] = useState<string[]>([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null);
  const [isEditing, setIsEditing] = useState(false);
  const [editingNote, setEditingNote] = useState<Note | null>(null);
  const [viewingNote, setViewingNote] = useState<Note | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    loadNotes();
  }, []);

  const loadNotes = async () => {
    try {
      const notesData = await getAll<Note>(STORES.NOTES);
      const sorted = notesData.sort((a, b) => b.updatedAt - a.updatedAt);
      setNotes(sorted);

      // 提取分类
      const cats = [...new Set(sorted.map(n => n.category).filter(Boolean))];
      setCategories(cats);
    } catch (error) {
      console.error('[NotesPage] Load error:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const handleSaveNote = async () => {
    if (!editingNote) return;

    try {
      const note: Note = {
        ...editingNote,
        updatedAt: Date.now()
      };

      await put(STORES.NOTES, note);
      await loadNotes();
      setIsEditing(false);
      setEditingNote(null);
      toast.success('笔记已保存');
    } catch (error) {
      console.error('[NotesPage] Save error:', error);
      toast.error('保存失败');
    }
  };

  const handleDeleteNote = async (noteId: string) => {
    try {
      await remove(STORES.NOTES, noteId);
      await loadNotes();
      toast.success('笔记已删除');
    } catch (error) {
      console.error('[NotesPage] Delete error:', error);
      toast.error('删除失败');
    }
  };

  const handleExportNotes = () => {
    const content = filteredNotes.map(note => (
      `# ${note.title}\n\n` +
      `分类: ${note.category || '未分类'}\n` +
      `创建时间: ${new Date(note.createdAt).toLocaleString()}\n\n` +
      `${note.content}\n\n` +
      `---\n\n`
    )).join('');

    downloadFile(content, `notes_${new Date().toISOString().split('T')[0]}.md`, 'text/markdown');
    toast.success('笔记已导出');
  };

  const handleNewNote = () => {
    setEditingNote({
      id: generateId(),
      title: '',
      content: '',
      category: selectedCategory || '',
      isAutoGenerated: false,
      createdAt: Date.now(),
      updatedAt: Date.now()
    });
    setIsEditing(true);
  };

  const filteredNotes = notes.filter(note => {
    const matchesSearch = 
      note.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      note.content.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesCategory = !selectedCategory || note.category === selectedCategory;
    return matchesSearch && matchesCategory;
  });

  if (isLoading) {
    return (
      <div className="space-y-6">
        <div className="skeleton h-12 rounded-lg" />
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {[1, 2, 3].map(i => (
            <div key={i} className="skeleton h-48 rounded-xl" />
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-fade-in">
      {/* 页面标题 */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2">
            <NotebookPen className="w-6 h-6 text-indigo-400" />
            笔记本
          </h1>
          <p className="text-slate-400 mt-1">共 {notes.length} 条笔记</p>
        </div>

        <div className="flex items-center gap-3">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
            <Input
              placeholder="搜索笔记..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-10 w-48 bg-slate-800/50 border-slate-700"
            />
          </div>
          <Button variant="outline" onClick={handleExportNotes}>
            <Download className="w-4 h-4" />
          </Button>
          <Button onClick={handleNewNote}>
            <Plus className="w-4 h-4 mr-2" />
            新建笔记
          </Button>
        </div>
      </div>

      {/* 分类筛选 */}
      {categories.length > 0 && (
        <div className="flex flex-wrap gap-2">
          <Badge
            variant={selectedCategory === null ? 'default' : 'secondary'}
            className="cursor-pointer"
            onClick={() => setSelectedCategory(null)}
          >
            全部
          </Badge>
          {categories.map(cat => (
            <Badge
              key={cat}
              variant={selectedCategory === cat ? 'default' : 'secondary'}
              className="cursor-pointer"
              onClick={() => setSelectedCategory(cat)}
            >
              {cat}
            </Badge>
          ))}
        </div>
      )}

      {/* 笔记列表 */}
      {filteredNotes.length === 0 ? (
        <div className="text-center py-16">
          <NotebookPen className="w-16 h-16 text-slate-600 mx-auto mb-4" />
          <h3 className="text-xl font-semibold mb-2">
            {searchQuery ? '没有找到匹配的笔记' : '还没有笔记'}
          </h3>
          <p className="text-slate-400 mb-6">
            {searchQuery ? '尝试其他关键词' : '创建你的第一条笔记吧'}
          </p>
          {!searchQuery && (
            <Button onClick={handleNewNote}>
              <Plus className="w-4 h-4 mr-2" />
              新建笔记
            </Button>
          )}
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {filteredNotes.map((note) => (
            <Card
              key={note.id}
              className="glass-card group hover:border-indigo-500/30 transition-all cursor-pointer"
              onClick={() => setViewingNote(note)}
            >
              <CardContent className="p-4">
                <div className="flex items-start justify-between mb-2">
                  <h3 className="font-semibold truncate flex-1">{note.title || '无标题'}</h3>
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button variant="ghost" size="icon" className="h-8 w-8 opacity-0 group-hover:opacity-100" onClick={(e) => e.stopPropagation()}>
                        <MoreVertical className="w-4 h-4" />
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end" className="glass-panel">
                      <DropdownMenuItem onClick={(e) => { e.stopPropagation(); setViewingNote(note); }}>
                        <Eye className="w-4 h-4 mr-2" />
                        查看
                      </DropdownMenuItem>
                      <DropdownMenuItem onClick={(e) => { e.stopPropagation(); setEditingNote(note); setIsEditing(true); }}>
                        <Edit3 className="w-4 h-4 mr-2" />
                        编辑
                      </DropdownMenuItem>
                      <DropdownMenuItem onClick={(e) => { e.stopPropagation(); handleDeleteNote(note.id); }} className="text-red-400">
                        <Trash2 className="w-4 h-4 mr-2" />
                        删除
                      </DropdownMenuItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                </div>

                {note.category && (
                  <Badge variant="secondary" className="mb-2">{note.category}</Badge>
                )}

                <p className="text-slate-400 text-sm line-clamp-3 mb-3">
                  {note.content || '无内容'}
                </p>

                <div className="flex items-center justify-between text-xs text-slate-500">
                  <span>{new Date(note.updatedAt).toLocaleDateString()}</span>
                  {note.isAutoGenerated && (
                    <Badge variant="outline" className="text-xs">AI生成</Badge>
                  )}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {/* 编辑对话框 */}
      <Dialog open={isEditing} onOpenChange={setIsEditing}>
        <DialogContent className="glass-panel max-w-3xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>{editingNote?.id ? '编辑笔记' : '新建笔记'}</DialogTitle>
          </DialogHeader>
          
          {editingNote && (
            <div className="space-y-4 mt-4">
              <div>
                <label className="text-sm font-medium mb-2 block">标题</label>
                <Input
                  value={editingNote.title}
                  onChange={(e) => setEditingNote({ ...editingNote, title: e.target.value })}
                  placeholder="笔记标题"
                />
              </div>

              <div>
                <label className="text-sm font-medium mb-2 block">分类</label>
                <Input
                  value={editingNote.category}
                  onChange={(e) => setEditingNote({ ...editingNote, category: e.target.value })}
                  placeholder="分类（可选）"
                />
              </div>

              <div>
                <label className="text-sm font-medium mb-2 block">内容</label>
                <Textarea
                  value={editingNote.content}
                  onChange={(e) => setEditingNote({ ...editingNote, content: e.target.value })}
                  placeholder="笔记内容（支持 Markdown）"
                  className="min-h-[300px] font-mono"
                />
              </div>

              <div className="flex justify-end gap-2">
                <Button variant="outline" onClick={() => setIsEditing(false)}>
                  <X className="w-4 h-4 mr-2" />
                  取消
                </Button>
                <Button onClick={handleSaveNote}>
                  <Save className="w-4 h-4 mr-2" />
                  保存
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* 查看详情对话框 */}
      <Dialog open={!!viewingNote} onOpenChange={(open) => !open && setViewingNote(null)}>
        <DialogContent className="glass-panel max-w-3xl max-h-[85vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <NotebookPen className="w-5 h-5 text-indigo-400" />
              {viewingNote?.title || '无标题'}
            </DialogTitle>
          </DialogHeader>
          {viewingNote && (
            <div className="space-y-4 mt-2">
              <div className="flex items-center gap-3 text-sm text-slate-400">
                {viewingNote.category && (
                  <Badge variant="secondary">{viewingNote.category}</Badge>
                )}
                <span>创建于 {new Date(viewingNote.createdAt).toLocaleDateString()}</span>
                {viewingNote.isAutoGenerated && (
                  <Badge variant="outline" className="text-xs">AI生成</Badge>
                )}
              </div>
              <div className="prose prose-invert max-w-none text-slate-200 whitespace-pre-wrap">
                {viewingNote.content || '无内容'}
              </div>
              <div className="flex justify-end gap-2 pt-4 border-t border-slate-700/30">
                <Button variant="outline" onClick={() => setViewingNote(null)}>关闭</Button>
                <Button onClick={() => { setEditingNote(viewingNote); setViewingNote(null); setIsEditing(true); }}>
                  <Edit3 className="w-4 h-4 mr-2" />编辑
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
