/**
 * CodeSpirit 类型定义
 */

// 课程状态
export type CourseStatus = 'draft' | 'generating' | 'active' | 'completed' | 'archived';

// 章节状态
export type ChapterStatus = 'locked' | 'available' | 'in_progress' | 'completed';

// 难度级别
export type Difficulty = 'beginner' | 'easy' | 'medium' | 'hard' | 'expert';

// 课程语言
export type CourseLanguage = 'zh-CN' | 'en-US';

// 课程数据结构
export interface Course {
  id: string;
  title: string;
  description: string;
  coverImage: string;
  language: CourseLanguage;
  status: CourseStatus;
  difficulty: Difficulty;
  totalChapters: number;
  completedChapters: number;
  estimatedHours: number;
  tags: string[];
  createdAt: number;
  updatedAt: number;
  lastStudiedAt: number | null;
  creatorInfo?: {
    name: string;
    watermark?: string;
  };
  isEncrypted?: boolean;
  passwordHash?: string;
}

// 章节数据结构
export interface Chapter {
  id: string;
  courseId: string;
  order: number;
  title: string;
  status: ChapterStatus;
  content?: string;
  structuredContent?: string | any; // 结构化内容（JSON字符串或对象）
  stages?: Stage[];
  currentStageIndex: number;
  estimatedMinutes: number;
  xpReward: number;
  createdAt: number;
  updatedAt: number;
}

// 学习阶段
export interface Stage {
  id: string;
  name: string;
  type: 'explanation' | 'example' | 'practice' | 'test' | 'summary';
  content: string;
  completed: boolean;
}

// 游戏化组件类型
export type GameType = 
  | 'game-maze'
  | 'game-puzzle'
  | 'game-drag-drop'
  | 'game-multi-choice'
  | 'game-code-exec'
  | 'game-custom'
  | 'game-fill-blank'
  | 'game-mini-project';

// 游戏组件数据
export interface GameComponent {
  type: GameType;
  id: string;
  data: Record<string, any>;
}

// 用户统计数据
export interface UserStats {
  xp: number;
  level: number;
  streakDays: number;
  lastStudyDate: string | null;
  totalStudyTime: number; // 分钟
  totalCodeSubmissions: number;
  correctRate: number;
  coursesCompleted: number;
  chaptersCompleted: number;
  badges: Badge[];
  checkInHistory: CheckInRecord[];
}

// 徽章
export interface Badge {
  id: string;
  name: string;
  description: string;
  icon: string;
  unlockedAt: number;
  category: 'achievement' | 'milestone' | 'special';
}

// 打卡记录
export interface CheckInRecord {
  date: string;
  xpEarned: number;
  isMakeup: boolean;
}

// 笔记
export interface Note {
  id: string;
  courseId?: string;
  chapterId?: string;
  title: string;
  content: string;
  category: string;
  isAutoGenerated: boolean;
  sourceText?: string;
  createdAt: number;
  updatedAt: number;
}

// 作品
export interface Work {
  id: string;
  courseId?: string;
  chapterId?: string;
  title: string;
  description: string;
  type: 'image' | 'link' | 'code';
  content: string;
  category: string;
  createdAt: number;
}

// 学习进度
export interface Progress {
  id: string;
  courseId: string;
  chapterId: string;
  completed: boolean;
  score: number;
  timeSpent: number;
  attempts: number;
  mistakes: string[];
  lastAccessedAt: number;
  updatedAt: number;
}

// 应用设置
export interface AppSettings {
  language: CourseLanguage;
  theme: 'light' | 'dark' | 'system';
  primaryColor: string;
  fontSize: number;
  fontFamily: string;
  soundEnabled: boolean;
  ttsEnabled: boolean;
  autoGenerateCount: number;
  focusMode: boolean;
}

// AI配置
export interface AIConfiguration {
  provider: string;
  endpoint: string;
  model: string;
  apiKeys: string[];
  temperature: number;
  maxTokens: number;
  keyIndex: number;
}

// 用户资料
export interface UserProfile {
  nickname: string;
  avatar: string;
  aiRole: 'mentor' | 'friend' | 'expert';
  aiRoleName: string;
}

// 看板组件配置
export interface DashboardWidget {
  id: string;
  type: string;
  title: string;
  visible: boolean;
  order: number;
  config?: Record<string, any>;
}

// 课程方案
export interface CoursePlan {
  title: string;
  description: string;
  focus: string;
  estimatedWeeks: number;
  style?: string;
  learningStyle?: string;
  keyFeatures?: string[];
}

// 代码执行结果
export interface CodeExecutionResult {
  success: boolean;
  output: string;
  error?: string;
  executionTime: number;
}

// AI消息
export interface AIMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
  timestamp?: number;
}

// 导出/导入数据格式
export interface ExportData {
  version: number;
  exportDate: string;
  courses: Course[];
  chapters: Chapter[];
  notes: Note[];
  works: Work[];
  progress: Progress[];
  stats: UserStats;
  settings: AppSettings;
}
